spring:

  application:
    name: user-demo

  datasource:
    driver-class-name: Enter your driver-class-name
    url: Enter your url
    username: Enter your username
    password: Enter your password

  session:
    timeout: 86400


server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

    #指定逻辑删除字段名
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
